# Generated by Django 4.0.6 on 2022-07-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_jobpostactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostActivityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpostactivity')),
            ],
            options={
                'db_table': 'job_post_activity_status',
            },
        ),
    ]
