# Generated by Django 4.0.6 on 2022-07-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_jobpostactivitystatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostActivityStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interviewed', 'interviewed'), ('accepted', 'accepted'), ('offer in progress', 'offer in progress')], max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobpostactivity')),
            ],
            options={
                'db_table': 'job_post_activity_status_change',
            },
        ),
    ]
